### ISSUE TITLE
Scala 2.12.0 release

### ISSUE THREAD

**Issue by cquiroz** [scala-js/scala-js-java-logging#7]
Could we get a scala 2.12.0 release out?

**Comment by sjrd** [comment]
Hum, I thought I had published 0.1.0 for 2.12 final, but apparently I didn't.

I don't really have computer access with Internet for the weekend (I'm on mobile), so it might have to wait until Monday :-s

**Comment by cquiroz** [comment]
bump 😄

**Comment by sjrd** [comment]
Oops! Sorry, I forgot. Done. On its way to Maven Central.
