### ISSUE TITLE
Default log level should be INFO instead of ALL

### ISSUE THREAD

**Issue by xerial** [scala-js/scala-js-java-logging#8]
Is there any reason why the default log level is set to ALL instead of INFO?
https://github.com/scala-js/scala-js-java-logging/blob/01ec1bd3c1d5ded5d59275c641011673a4a8a67f/src/main/scala/java/util/logging/Logger.scala#L13

java.util.logging uses INFO as the default level of the root logger.

**Comment by sjrd** [comment]
If the JVM version uses `INFO` by default, so should we.

**Comment by xerial** [comment]
OK. Thanks. I'll create a PR for this.

Actually I'm working on supporting Scala.js in https://github.com/wvlet/log/pull/8. 
I found another issue in resolving parent loggers (the log message is not shown)  I'll send PR for this as well after finding the actual cause.
